# Generated by Django 3.2.7 on 2021-10-20 15:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="date",
            field=models.TextField(blank=True),
        ),
    ]
