# Generated by Django 3.2.7 on 2021-10-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parser_project", "0005_auto_20211024_1302"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={
                "ordering": ["-date", "-id"],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
