# Generated by Django 3.2.7 on 2021-11-22 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_project', '0008_articles_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='owner',
        ),
    ]
